# Generated by Django 5.1.3 on 2025-08-29 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0012_unitofmeasure_alter_product_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitofmeasure',
            old_name='abbreviation',
            new_name='short_name',
        ),
    ]
