# Generated by Django 5.1.3 on 2025-08-29 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0013_rename_abbreviation_unitofmeasure_short_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitOfMeasure',
            new_name='Unit',
        ),
    ]
