# Generated by Django 5.1.3 on 2025-09-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0014_rename_unitofmeasure_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unit',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='posApp.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('store', 'name')},
        ),
    ]
