# Generated by Django 5.1.3 on 2026-01-19 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0015_unit_status_unit_store_alter_unit_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='posApp.unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='posApp.unit'),
        ),
    ]
