# Generated by Django 5.1.3 on 2026-01-19 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0016_salesitem_unit_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cashiers',
            field=models.ManyToManyField(related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
