# Generated by Django 5.1.3 on 2026-01-28 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0017_store_cashiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_categories', models.BooleanField(default=True)),
                ('enable_units', models.BooleanField(default=True)),
                ('enable_expiry', models.BooleanField(default=False)),
                ('enable_barcode', models.BooleanField(default=True)),
                ('enable_low_stock_alert', models.BooleanField(default=True)),
                ('enable_discounts', models.BooleanField(default=True)),
                ('enable_credit_sales', models.BooleanField(default=False)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('receipt_footer', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='posApp.store')),
            ],
        ),
    ]
