# Generated by Django 4.2.27 on 2026-02-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0019_alter_salesitem_unit_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storesettings',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storesettings',
            name='show_tax',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='show_total',
            field=models.BooleanField(default=True),
        ),
    ]
