# Generated by Django 4.2.27 on 2026-02-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0020_storesettings_address_storesettings_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='phone',
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
