# Generated by Django 4.2.27 on 2026-02-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0021_remove_storesettings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
